# Generated by Django 5.1 on 2025-12-24 07:30

import base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.managers.UserManager()),
            ],
        ),
    ]
